kotlin.code.style=official

# project id
projectGroupId=io.github.smiley4
projectArtifactId=ktor-plus
projectVersion=0.1.0

# common publishing information
projectBaseScmUrl=https://github.com/SMILEY4/ktor-plus
projectBaseScmConnection=scm:git:git://github.com/SMILEY4/ktor-plus.git
projectLicenseName=The Apache License, Version 2.0
projectLicenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
projectDeveloperName=smiley4
projectDeveloperUrl=https://github.com/SMILEY4

# dependency versions